# Generated by Django 4.1.7 on 2023-03-19 21:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='dislikes',
            field=models.ManyToManyField(related_name='answer_dislikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
