# Generated by Django 4.1.7 on 2023-03-17 10:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_question_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
