# Generated by Django 4.1.7 on 2023-03-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_answer_date_alter_question_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
