# Generated by Django 4.1.7 on 2023-03-19 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_profile_badges'),
        ('main_app', '0017_alter_question_body'),
    ]

    operations = [
    ]
