# Generated by Django 4.1.7 on 2023-03-19 17:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0018_merge_0015_profile_badges_0017_alter_question_body'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Badges',
            new_name='Badge',
        ),
        migrations.AddField(
            model_name='answer',
            name='likes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
